customers/views.py
import os
from flask import Blueprint, json, jsonify, render_template, request, redirect, flash, session, url_for
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, null, text
from contextlib import contextmanager
from campus_eats import UserTable, Customer , OrderTable, OrderDetail
from datetime import date, datetime, timedelta

# 建立實體
customers_blueprints = Blueprint('customers', __name__, template_folder='templates/customers', static_folder='./static')

# 創建資料庫引擎
# DATABASE_URL = 'mysql+pymysql://root:mysql@localhost/campus_eats'
DATABASE_URL = 'mysql+pymysql://root:@localhost/campus_eats' # Nicole
# DATABASE_URL = 'mysql+pymysql://root:113423027@mysql-1.cfg8ygkqmlab.ap-northeast-3.rds.amazonaws.com/campus_eats' # AWS

engine = create_engine(DATABASE_URL)
Session = sessionmaker(bind=engine)

# 創建一個上下文管理器來自動管理 Session 的生命週期
@contextmanager
def get_session():
    session = Session()
    try:
        yield session
        session.commit()  # 若有任何變更需要提交
    except Exception as e:
        session.rollback()  # 發生錯誤時回滾事務
        raise
    finally:
        session.close()  # 結束後關閉 session

@customers_blueprints.route('/menu')
def menu():
    # 返回菜單頁面
    return render_template('customers/view_store.html')

@customers_blueprints.route('/add_to_cart', methods=['GET', 'POST']) 
def add_to_cart():  # 新增餐點進購物車
    if request.method == 'POST':
        item_id = request.form['item_id']  # 現在要購買之餐點 id
        item_price = request.form['item_price'] # 目前購買的餐點價格
        redirect_flag = int(request.form.get('redirect_flag'))
        restaurant_id = get_restaurant_id_for_item(item_id) # 目前購買餐點的所屬餐廳
        customer_id = session.get('customer_id')  # 目前使用者 id
        all_active_orders = check_existing_orders(customer_id) # 目前有的購物車
    
        # 檢查是否已存在相同餐廳的訂單
        existing_order = None
        for order in all_active_orders: # 如果有抓取現有的
            if order['restaurant_id'] == restaurant_id:
                existing_order = order['order_id']
                break

        if not existing_order: # 如果無則建立新的訂單
            existing_order = checkOrder(customer_id)
            
        add_one_item_in_Cart(item_id, existing_order,item_price)
        if redirect_flag == 1:
            return redirect(url_for('customers.view_cart'))
            
        else:
            return redirect(url_for('menus.view_menu', restaurant_id=restaurant_id))

def add_one_item_in_Cart(item_id, order_id,item_price):  # 新增一份餐點進入購物車
    with get_session() as db_session:
        existing_order_detail = db_session.query(OrderDetail).filter_by(  # 確認目前是否有同筆商品的訂單細項
                order_id=order_id,
                item_id=item_id
            ).first()
        if existing_order_detail:  # 如果有則直接將數量加一
            existing_order_detail.quantity += 1
            db_session.commit()  # 提交變更
        else:
            new_order_detail = OrderDetail(
                order_id=order_id,
                item_id=item_id,
                item_price = item_price,
                quantity=1  # 新增時初始數量為 1
            )
            db_session.add(new_order_detail)
            db_session.commit()  # 提交新記錄

def checkOrder(customer_id):  # 新增一筆新的訂單
    with get_session() as db_session:
        current_time = datetime.now()  # 記錄下訂單的時間
        new_order = OrderTable(
            order_status=0,
            total_amount=0,
            payment_status=0,
            customer_id=customer_id,
            order_time=current_time,
            order_pick_up_time = current_time
        )
        db_session.add(new_order)
        db_session.commit()

        # 獲取新建訂單的 ID
        db_session.refresh(new_order)  # 刷新以獲取新插入的 id
        return new_order.order_id if new_order else None

def get_restaurant_id_for_item(item_id): # 查詢該產品所屬的店家
    with get_session() as db_session:
        query = text("""
            SELECT restaurant_id
            FROM menu_item
            WHERE item_id = :item_id;
            """)
        result = db_session.execute(query, {"item_id": item_id}).scalar()
        return result if result else None
    
def check_existing_orders(customer_id): # 查當前用戶擁有的所有購物車
    # 查找所有屬於該使用者且狀態為零的訂單
    with get_session() as db_session:
        query = text("""
            SELECT order_id
            FROM order_table
            WHERE customer_id = :customer_id AND order_status = 0;
            """)
        orders = db_session.execute(query, {"customer_id": customer_id}).fetchall()
    
    # 根據訂單的 id 去訂單細項表格隨便抓取一格內容商品，並在通過該商品之編號去menu表格裡查詢所屬店家
    restaurant_ids = []
    for order in orders:
        order_id = order[0]
        # 從訂單細項表中隨便抓取一筆內容商品
        with get_session() as db_session:
            item_query = text("""
                SELECT item_id
                FROM order_detail
                WHERE order_id = :order_id
                LIMIT 1;
                """)
            item_id = db_session.execute(item_query, {"order_id": order_id}).scalar()
        
        if item_id:
            # 通過該商品的編號去 menu_item 表格查詢所屬店家
            restaurant_id = get_restaurant_id_for_item(item_id)
            if restaurant_id:
                restaurant_ids.append({"order_id": order_id, "restaurant_id": restaurant_id})

    return restaurant_ids

@customers_blueprints.route('/view_cart')
def view_cart(): # 查看購物車內容
    customer_id = session.get('customer_id')  # 目前使用者 id
    customer_name = session.get('customer_name')
    order_list = fetch_cart_item(customer_id) # 目前所有購物車資料
    return render_template('customers/view_cart.html',cart_items = order_list,customer_name = customer_name)

def fetch_cart_item(customer_id):  # 抓取目前所擁有的所有購物車
    with get_session() as session:
        query = text("""
            SELECT order_table.order_id, order_table.order_note, order_detail.order_detail_id, order_detail.item_id, 
                   menu_item.item_name, menu_item.price, order_detail.quantity, order_detail.item_note, 
                   menu_item.restaurant_id, restaurant.restaurant_name, restaurant.business_hours
            FROM order_table
            JOIN order_detail ON order_table.order_id = order_detail.order_id
            JOIN menu_item ON order_detail.item_id = menu_item.item_id
            JOIN restaurant ON restaurant.restaurant_id = menu_item.restaurant_id
            WHERE order_table.order_status = 0 AND order_table.customer_id = :customer_id;
        """)
        result = session.execute(query, {"customer_id": customer_id}).fetchall()
        
        # 使用字典來分組資料
        grouped_cart_items = {}
        for row in result:
            order_id = row[0]
            order_note = row[1]
            order_detail_id = row[2]
            item_id = row[3]
            item_name = row[4]
            item_price = row[5]
            item_quantity = row[6]
            item_note = row[7]
            restaurant_id = row[8]
            restaurant_name = row[9]
            restaurant_business_hours= row[10]

            # 計算單筆商品的小計
            item_total_price = item_price * item_quantity
            available_times = get_available_times(restaurant_business_hours)
            
            # 如果這個餐廳還沒有被添加到字典中
            if restaurant_id not in grouped_cart_items:
                grouped_cart_items[restaurant_id] = {
                    "restaurant_name": restaurant_name,
                    "order_id": order_id,  # 新增 order_id 到與 restaurant_id 同一層
                    "order_note": order_note,  # 新增整筆訂單的備註
                    "items": [],
                    "total_price": 0,
                    "available_times": available_times
                }
            
            # 將商品資訊添加到對應餐廳的 items 列表中
            grouped_cart_items[restaurant_id]["items"].append({
                "order_detail_id": order_detail_id,
                "order_id": order_id,
                "item_id": item_id,
                "item_name": item_name,
                "price": item_price,
                "quantity": item_quantity,
                "item_note": item_note,  # 為每個商品新增細項備註
                "item_total_price": item_total_price  # 計算單筆商品的小計
            })

            # 增加餐廳的總金額
            grouped_cart_items[restaurant_id]["total_price"] += item_total_price

        print(grouped_cart_items)
    return grouped_cart_items

def get_available_times(business_hours): # 生成可以取餐的時間
    # 取得目前的日期和時間
    now = datetime.now()
    weekday_map = {
        0: 'Monday',
        1: 'Tuesday',
        2: 'Wednesday',
        3: 'Thursday',
        4: 'Friday',
        5: 'Saturday',
        6: 'Sunday'
    }
    
    # 取得今天是星期幾
    today_weekday = weekday_map[now.weekday()]
    
    # 解析 restaurant_business_hours 中的營業時間
    business_hours_dict = {}
    for day_info in business_hours.split(", "):
        day, hours = day_info.split(": ")
        business_hours_dict[day] = hours

    # 獲取今天的營業時間
    today_hours = business_hours_dict.get(today_weekday)
    if today_hours is None or today_hours == 'Closed':
        return []  # 今日不營業，回傳空列表

    # 解析今天的營業時間
    open_time_str, close_time_str = today_hours.split("~")
    open_time = datetime.strptime(open_time_str, "%H:%M").replace(year=now.year, month=now.month, day=now.day)
    close_time = datetime.strptime(close_time_str, "%H:%M").replace(year=now.year, month=now.month, day=now.day)
    
    # 若目前時間超過營業結束時間，回傳空列表
    if now >= close_time:
        return []

    # 計算最早可取餐時間為現在時間的15分鐘後
    earliest_pickup_time = now + timedelta(minutes=15)

    # 將最早可取餐時間調整到最近的整點、15分、30分或45分
    minute = earliest_pickup_time.minute
    if minute < 15:
        adjusted_minute = 15
    elif minute < 30:
        adjusted_minute = 30
    elif minute < 45:
        adjusted_minute = 45
    else:
        adjusted_minute = 0
        earliest_pickup_time += timedelta(hours=1)

    # 更新最早取餐時間
    earliest_pickup_time = earliest_pickup_time.replace(minute=adjusted_minute, second=0, microsecond=0)

    # 計算目前時間到營業結束時間的可選擇時間，並確保最早的取餐時間為調整後的時間
    available_times = []
    current_time = max(earliest_pickup_time, open_time)  # 確保時間從營業開始時間後開始

menus/views.py
import os
from contextlib import contextmanager
from flask import Blueprint, render_template, session, redirect, url_for, request, flash
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from campus_eats import Restaurant, MenuItem
from datetime import datetime, timezone, timedelta


menus_blueprints = Blueprint('menus', __name__, static_folder='./static')

# 創建資料庫引擎
# DATABASE_URL = 'mysql+pymysql://root:mysql@localhost/campus_eats'
DATABASE_URL = 'mysql+pymysql://root:@localhost/campus_eats' # Nicole
# DATABASE_URL = 'mysql+pymysql://root:113423027@mysql-1.cfg8ygkqmlab.ap-northeast-3.rds.amazonaws.com/campus_eats' # AWS

engine = create_engine(DATABASE_URL)
Session = sessionmaker(bind=engine)


# 創建一個上下文管理器來自動管理 Session 的生命週期
@contextmanager
def get_session():
    session = Session()
    try:
        yield session
        session.commit()  # 若有任何變更需要提交
    except Exception as e:
        session.rollback()  # 發生錯誤時回滾事務
        raise
    finally:
        session.close()  # 結束後關閉 session



@menus_blueprints.route('/view_store')
def view_store():
    if not session.get('role'):
        return redirect(url_for('auth.login'))

    with get_session() as db_session:
        store_info = db_session.query(Restaurant).all()

        # 定義台灣時區
        taiwan_tz = timezone(timedelta(hours=+8))

        # 取得當前台灣的日期和時間
        now = datetime.now(taiwan_tz)
        current_day = now.strftime("%A")  # 當前星期
        current_time = now.time()  # 當前時間

        print("current_time: ", current_time)

        valid_stores = []

        for store in store_info:
            raw_business_hours = store.business_hours
            if not raw_business_hours:
                continue  # 無營業時間資料的店家跳過

            # 找出當天的營業時間
            try:
                today_hours = next(
                    (times for day, times in (entry.split(": ") for entry in raw_business_hours.split(", ")) if day == current_day),
                    None
                )
                if not today_hours:
                    continue  # 如果當天無營業時間則跳過
            except ValueError:
                continue  # 格式錯誤的營業時間跳過

            # 分割時間區間並檢查是否符合當前時間
            is_open = any(
                start <= current_time <= end
                for start, end in (
                    map(lambda t: datetime.strptime(t.strip(), "%H:%M").time(), time_range.split("~"))
                    for time_range in today_hours.split("、")
                )
            )
            if is_open:
                valid_stores.append({
                    "restaurant_id": store.restaurant_id,
                    "restaurant_name": store.restaurant_name,
                    "phone": store.phone,
                    "address": store.address,
                    "business_hours": store.business_hours,
                    "icon": store.icon
                })

        # 將營業中的店家資料傳遞到模板
        data = {"customer_name": session.get('customer_name'), "openedRestaurants": valid_stores}

    return render_template('customers/view_store.html', **data)
    


@menus_blueprints.route('/view_menu/<int:restaurant_id>')
def view_menu(restaurant_id):
    role = session.get('role')
    if not role:
        return redirect(url_for('auth.login'))
    
    with get_session() as db_session:
        menu_info = db_session.query(MenuItem).filter_by(restaurant_id=restaurant_id).all()
        restaurant_info = db_session.query(Restaurant).filter_by(restaurant_id=restaurant_id).first()
        
        restaurant_data = {
            "restaurant_name": restaurant_info.restaurant_name,
            "phone": restaurant_info.phone,
            "address": restaurant_info.address,
            "business_hours": restaurant_info.business_hours,
            "icon": restaurant_info.icon
        }
        # 將 MenuItem 的資料提取為字典
        menu_items = [
            {
                "item_id": item.item_id,
                "item_name": item.item_name,
                "price": item.price,
                "description": item.description,
                "status": item.status,
                "item_image": item.item_image
            }
            for item in menu_info
        ]

    if role == 1:
        data = {
            "username": session.get('username'),
            "customer_id": session.get('customer_id'),
            "customer_name": session.get('customer_name'),
            "restaurant": restaurant_data,
            "menu_items": menu_items  # 使用轉換過的資料
        }
        return render_template('customers/view_menu.html', **data)
    else:
        # 包裝資料以傳遞給模板
        data = {
            "restaurant_id": restaurant_id,
            "restaurant_name": session.get('restaurant_name'),
            "icon": session.get('icon'),
            "menu_items": menu_items  # 使用轉換過的資料
        }
        return render_template('restaurants/management.html', **data)


@menus_blueprints.route('/view_detailed_menu/<int:item_id>')
def view_detailed_menu(item_id):
    with get_session() as db_session:
        menu_info = db_session.query(MenuItem).filter_by(item_id=item_id).first()

        data = {
                "restaurant_id": session.get('restaurant_id'),
                "restaurant_name": session.get('restaurant_name'),
                "icon": session.get('icon'),
                "item_id": menu_info.item_id,
                "item_name": menu_info.item_name,
                "price": menu_info.price,
                "description": menu_info.description,
                "status": menu_info.status,
                "item_image": menu_info.item_image
            }

    return render_template('restaurants/modify_item.html', **data)

templates/customers/index.html
<h1>Hello customer index</h1>

templates/customers/view_cart.html
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NCU Campus Eats | 目前訂單</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='customers/view_cart.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='customers/navbar.css') }}">
</head>
<body>
    <!-- 頂部導航欄 -->
    <header class="navbar">
        <!-- 左側LOGO和標題 -->
        <a href="{{ url_for('menus.view_store') }}" class="logo">
            <img src="{{ url_for('static', filename='images/NCUlogo.png') }}" alt="LOGO">
            <span>NCU Campus Eats | 購物車</span>
        </a>

        <!-- 右側按鈕與下拉選單 -->
        <div class="menu">
            <a href="{{ url_for('customers.view_cart') }}">
                <button class="cart-button" >
                    <img src="{{ url_for('static', filename='images/cart.png') }}" alt="Cart">
                </button>
            </a>
            <div class="dropdown">
                <img src="{{ url_for('static',filename='images/customer.png') }}" alt="Photo"> <!-- 替換為店家Icon的URL -->
                <span>{{ customer_name }}</span>
                <div class="dropdown-menu">
                    <a href="{{ url_for('customers.view_order') }}">歷史訂單</a>
                    <a href="{{ url_for('customers.view_pf') }}">修改個人資料</a>
                    <a href="{{ url_for('auth.change_password') }}">修改密碼</a>
                    <a href="{{ url_for('auth.logout') }}">登出</a>
                </div>
            </div>
        </div>
    </header>

    <div id='shopping-cart'>
        <h1>購物車內容物</h1>
        {% if cart_items %}
            {% for restaurant_id, restaurant_info in cart_items.items() %}
                <div class="restaurant-section">
                    <h2>店家：{{ restaurant_info['restaurant_name'] }}</h2>
                    <table class="cart-table">
                        <thead>
                            <tr>
                                <th>餐點名稱</th>
                                <th>餐點單價</th>
                                <th>購物車內數量</th>
                                <th>餐點備註</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in restaurant_info['items'] %}
                                <tr>
                                    <td>{{ item['item_name'] }}</td>
                                    <td>{{ item['price'] }} 元</td>
                                    <td>{{ item['quantity'] }}</td>
                                    <td>
                                        {% if item['item_note'] %}
                                            {{ item['item_note'] }}
                                        {% else %}
                                            目前無備註
                                        {% endif %}
                                    </td>
                                    <td class="action-column">
                                        <div class="action-buttons">
                                            <form action="{{ url_for('customers.add_to_cart') }}" method="post" onsubmit="return confirmAction('{{ item.item_name }}', 'add')">
                                                <input type="hidden" name="item_id" value="{{ item['item_id'] }}">
                                                <input type="hidden" name="item_price" value="{{ item['price'] }}">
                                                <input type="hidden" name="redirect_flag" value="1">
                                                <button type="submit" class="button button-add">再新增「1」份至購物車</button>
                                            </form>
                                            <form action="{{ url_for('customers.remove_from_cart') }}" method="post" onsubmit="return confirmAction('{{ item.item_name }}', 'remove')">
                                                <input type="hidden" name="order_id" value="{{ restaurant_info['order_id'] }}">
                                                <input type="hidden" name="order_detail_id" value="{{ item['order_detail_id'] }}">
                                                <button type="submit" class="button button-remove">從購物車中移除「1」份</button>
                                            </form>
                                            <button class="button add-note-button" onclick="openNoteModal('{{ restaurant_info.order_id }}', '{{ item.order_detail_id }}')">
                                                新增餐點備註
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <p class="total-amount"><strong>總金額：{{ restaurant_info['total_price'] }} 元</strong></p>
                    <p>
                        <strong>目前備註：</strong>
                        {% if restaurant_info['order_note'] %}
                            {{ restaurant_info['order_note'] }}
                        {% else %}
                            目前無備註
                        {% endif %}
                    </p>
                    <div class="action-buttons">
                        <form action="{{ url_for('customers.delete_order') }}" method="post" onsubmit="return confirmDeleteOrder()">
                            <input type="hidden" name="order_id" value="{{ restaurant_info['order_id'] }}">
                            <button type="submit" class="button delete-order-button">刪除整筆訂單</button>
                        </form>
                        <button class="button add-note-button" onclick="openOrderNoteModal('{{ restaurant_info.order_id }}')">為整筆訂單新增備註</button>
                        <button class="button checkout-button" onclick="openPaymentModal('{{ restaurant_info.order_id }}', '{{ restaurant_info.total_price }}', '{{ restaurant_id }}', '{{ restaurant_info.available_times }}')">前往結帳</button>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>目前沒有任何未送出的訂單。</p>
        {% endif %}
    </div>
    
    

    <!-- 付款方式模態框 -->
    <div id="paymentModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closePaymentModal()">&times;</span>
            <h2>選擇付款方式</h2>
            <form id="paymentForm" action="{{ url_for('customers.checkout_order') }}" method="post" onsubmit="return confirmAction('', 'checkout')">
                <input type="hidden" id="paymentOrderId" name="order_id">
                <input type="hidden" id="totalPrice" name="total_price">
                <input type="hidden" id="restaurantID" name="restaurant_id">
                <label for="payment_method">請選擇付款方式：</label><br><br>
                <select id="payment_method" name="payment_method" required>
                    <option value="" disabled selected>選擇付款方式</option>
                    <option value="1">現金</option>
                    <!--<option value="2">信用卡</option>-->
                </select>
                <br><br>

                <label for="pickup_time">請選擇取餐時間：</label><br><br>
                <select id="pickup_time" name="pickup_time" required>
                    <option value="" disabled selected>選擇取餐時間</option>
                </select>
                <br><br>
                
                <div class="modal-actions">
                    <button type="button" onclick="submitPayment()">提交</button>
                    <button type="button" onclick="closePaymentModal()">取消</button>
                </div>
            </form>
        </div>
    </div>

    <!-- 新增備註的模態框 -->
    <div id="noteModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeNoteModal()">&times;</span>
            <h2>新增備註</h2>
            <form id="noteForm" action="{{ url_for('customers.add_note') }}" method="post">
                <input type="hidden" id="noteOrderId" name="order_id">
                <input type="hidden" id="noteDetailId" name="order_detail_id">
                <label for="note">請輸入備註內容：</label>
                <textarea id="note" name="note" rows="4" required></textarea>
                <div class="modal-actions">
                    <button type="button" onclick="submitNote()">提交</button>
                    <button type="button" onclick="closeNoteModal()">取消</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        function confirmAction(itemName, action) {
            let message = "";
            if (action === "add") {
                message = "你確定要將 " + itemName + " 加入「1」份至購物車嗎？";
            } else if (action === "remove") {
                message = "你確定要將 " + itemName + " 從購物車中移除「1」份嗎？";
            } else if (action === "checkout") {
                message = "你確定要進行結帳嗎？";
            }

            if (confirm(message)) {
                if (action === "add") {
                    alert(itemName + " 新增成功！");
                } else if (action === "remove") {
                    alert(itemName + " 移除成功！");
                } else if (action === "checkout") {
                    alert("訂單結帳成功！");
                }
                return true; // 允許表單提交
            } else {
                return false; // 阻止表單提交
            }
        }

        // 開啟備註模態框
        function openNoteModal(orderId, orderDetailId = null) {
            document.getElementById('noteOrderId').value = orderId;
            document.getElementById('noteDetailId').value = orderDetailId || '';
            document.getElementById('noteModal').style.display = 'block';
        }

        // 開啟整筆訂單備註模態框
        function openOrderNoteModal(orderId) {
            openNoteModal(orderId);
        }

        // 關閉備註模態框
        function closeNoteModal() {
            document.getElementById('noteModal').style.display = 'none';
        }

        // 提交備註
        function submitNote() {
            const form = document.getElementById('noteForm');
            form.submit();
        }

        // 開啟付款方式模態框
        function openPaymentModal(orderId, totalPrice, restaurantID, availableTimes) {
            // 將 availableTimes 解析為 JSON 格式，確保它變成 JavaScript 陣列
            availableTimes = JSON.parse(availableTimes);

            // 如果 availableTimes 為空，顯示警告訊息並關閉模態框
            if (availableTimes.length === 0) {
                alert("目前店家無營業或不收單，無法前往結帳。");
                closePaymentModal();
                return;
            }
            // 設定隱藏欄位的值
            document.getElementById('paymentOrderId').value = orderId;
            document.getElementById('totalPrice').value = totalPrice;
            document.getElementById('restaurantID').value = restaurantID;

            console.log('Available pickup times:', availableTimes);

            // 獲取取餐時間下拉選單元素
            const pickupTimeSelect = document.getElementById('pickup_time');

            // 清空下拉選單的內容
            pickupTimeSelect.innerHTML = '<option value="" disabled selected>選擇取餐時間</option>';

            // 將 availableTimes 內的選項添加到下拉選單中
            availableTimes.forEach(time => {
                const option = document.createElement('option');
                option.value = time;
                option.textContent = time;
                pickupTimeSelect.appendChild(option);
            });

            // 顯示模態框
            document.getElementById('paymentModal').style.display = 'block';
        }

        // 關閉付款方式模態框
        function closePaymentModal() {
            document.getElementById('paymentModal').style.display = 'none';
        }

        // 提交付款
        function submitPayment() {
            const paymentMethodSelect = document.getElementById('payment_method');
            const pickupTimeSelect = document.getElementById('pickup_time');

            const selectedPaymentMethod = paymentMethodSelect.value;
            const selectedPickupTime = pickupTimeSelect.value;

            if (selectedPaymentMethod === "" && selectedPickupTime === "") {
                alert("請選擇付款方式和取餐時間！");
                return;  // 阻止提交
            } else if  (selectedPaymentMethod === ""){
                alert("請選擇付款方式！");
                return;
            }else if (selectedPickupTime === ""){
                alert("請選擇取餐時間！");
                return;
            }
            const form = document.getElementById('paymentForm');
            form.submit();
        }
        
        // 刪除整筆訂單的警告
        function confirmDeleteOrder() {
            return confirm("你確定要刪除整筆嗎？此操作無法恢復！");
        }


    </script>
</body>
</html>

templates/customers/view_customer_pf.html
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NCU Campus Eats | 個人資料</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='customers/view_pf.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='customers/navbar.css') }}">
</head>
<body>
    <!-- 頂部導航欄 -->
    <header class="navbar">
        <!-- 左側LOGO和標題 -->
        <a href="{{ url_for('menus.view_store') }}" class="logo">
            <img src="{{ url_for('static', filename='images/NCUlogo.png') }}" alt="LOGO">
            <span>NCU Campus Eats | 個人資料</span>
        </a>

        <!-- 右側按鈕與下拉選單 -->
        <div class="menu">
            <a href="{{ url_for('customers.view_cart') }}">
                <button class="cart-button">
                    <img src="{{ url_for('static', filename='images/cart.png') }}" alt="Cart">
                </button>
            </a>
            <div class="dropdown">
                <img src="{{ url_for('static',filename='images/customer.png') }}" alt="Photo"> <!-- 替換為使用者Icon的URL -->
                <span>{{ customer_name }}</span>
                <div class="dropdown-menu">
                    <a href="{{ url_for('customers.view_order') }}">歷史訂單</a>
                    <a href="{{ url_for('customers.view_pf') }}">修改個人資料</a>
                    <a href="{{ url_for('auth.change_password') }}">修改密碼</a>
                    <a href="{{ url_for('auth.logout') }}">登出</a>
                </div>
            </div>
        </div>

    </header>

    <div class="container">
        <h2>修改個人資訊</h2>
        <form action="{{ url_for('customers.edit_profile') }}" method="post" onsubmit="return confirmEditProfile()">
            <label for="name">姓名：</label>
            <input type="text" id="name" name="name" placeholder="姓名" value="{{ customer_pf['name'] }}" required>
    
            <label for="phone">電話：</label>
            <input type="text" id="phone" name="phone" placeholder="電話 (請輸入十位數字)" pattern="\d{10}" value="{{ customer_pf['phone'] }}" required>
    
            <label for="email">電子郵件：</label>
            <input type="email" id="email" name="email" placeholder="電子郵件" value="{{ customer_pf['email'] }}" required>
    
            <button type="submit" class="btn-submit">修改</button>
        </form>
    </div>
    
    <script>
        // 確認修改個人資料的函數
        function confirmEditProfile() {
            return confirm("您確定要修改您的個人資料嗎？");
        }
    </script>

</body>
</html>